### ISSUE TITLE
Add market price data

### ISSUE THREAD

**Issue by smola** [smola/ree-demanda#1]

**Comment by JorgeGT** [comment]
I don't know if you're referring to this but you can get [a nice JSON file](http://www.esios.ree.es/Solicitar?fileName=PVPC_CURV_DD_20150218&fileType=txt&idioma=es) of the hourly price for small consumers [_(Término de Facturación de Energía Activa del PVPC)_](http://www.esios.ree.es/web-publica/pvpc/).

And now it seems that the demand and previsions can be obtained in almost JSON [here](https://demanda.ree.es/WSvisionaMovilesPeninsulaRest/resources/demandaGeneracionPeninsula?callback=angular.callbacks._2&curva=DEMANDA&fecha=2015-02-18), from the mobile version of the graphs. They even offer [tabulated data](https://demanda.ree.es/movil/peninsula/demanda/tablas/2)! Maybe the official API is around the corner... x)

**Comment by smola** [comment]
@JorgeGT Thanks!

**Comment by JorgeGT** [comment]
You're welcome! I didn't resist to put the data to the test... but I've yet to do anything useful with it! 
![ree_2015-02-15](https://cloud.githubusercontent.com/assets/1165351/6543924/5be49932-c534-11e4-84c7-067bb43f7da5.png)
